name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create headers config
      run: |
        echo '/*' > _headers
        echo '  Cross-Origin-Opener-Policy: same-origin' >> _headers
        echo '  Cross-Origin-Embedder-Policy: require-corp' >> _headers

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .